---
- name: Instalar e configurar o Elasticsearch
  hosts: localhost
  become: true

  tasks:
    - name: Instalar pacote gnupg
      apt:
        name: gnupg
        state: present
  
    - name: Importar chave GPG do Elasticsearch
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Adicionar repositório do Elasticsearch
      apt_repository:
        repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
        state: present
        filename: "elastic-7.x.list"
        update_cache: yes

    - name: Atualizar cache do APT
      apt:
        update_cache: yes

    - name: Instalar o Elasticsearch
      apt:
        name: elasticsearch
        state: present

    - name: Copiar arquivo de configuração
      template:
        src: elasticsearch.yml
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: root
        group: root
        mode: 0644
      notify: Reiniciar serviço Elasticsearch

  handlers:
    - name: Reiniciar serviço Elasticsearch
      service:
        name: elasticsearch
        state: restarted